### ISSUE TITLE
Compression converts `else if` to `elseif`

### ISSUE THREAD

**Issue by micahjon** [glslify/rollup-plugin-glslify#11]
Hi, I noticed that compressing this shader code:

```glsl
    }else
    if (mode == 1.0){ // GROW

        offsetStrength *= 0.25;
```

Results in the following string: 
`}elseif(mode==1.0){offsetStrength*=0.25;`

Where `else if` is converted to `elseif`

I'm guessing this is unintentional. My understanding is that `elseif` is not valid syntax for GLSL, or at least not widely supported. Thanks for looking into this.

**Comment by pschroen** [comment]
Hi, this would be an upstream issue as the logic is from [rollup-plugin-glsl](https://github.com/vwochnik/rollup-plugin-glsl).

If you're determined to resolve the issue you can create an issue there, or remove the newline so `else if` is on one line.

**Comment by pschroen** [comment]
Upstream issue vwochnik/rollup-plugin-glsl#6 for reference.
