### ISSUE TITLE
Transfer to glslify org

### ISSUE THREAD

**Issue by dy** [glslify/rollup-plugin-glslify#3]
Hello @pschroen!
Would you consider transfering this repository to @glslify org?
I am crating pinned repositories there and want to showlist standard bundlers on the main page, your plugin seems to be a perfect fit.
Cheers!

**Comment by pschroen** [comment]
Hi @dy, would love to, it's also featured on rollup's awesome plugins page.

https://github.com/rollup/awesome#other-file-imports

I can request to have the URL updated after the transfer.
Cheers!

**Comment by dy** [comment]
Ok, just sent an invitation.

**Comment by pschroen** [comment]
Alright, updated to the latest version of rollup, and transferred! 😄

**Comment by dy** [comment]
Sweet!
