### ISSUE TITLE
Doesn't cleanup GLSL code in output string

### ISSUE THREAD

**Issue by ajayns** [glslify/rollup-plugin-glslify#8]
The plugin should not only support imports using glslify but strip the code of comments, formatting and minify into a string.

This is performed by [rollup-plugin-glsl](https://www.npmjs.com/package/rollup-plugin-glsl) maybe we could port the feature over from there?

**Comment by pschroen** [comment]
Agreed, considering the compress option should default to true as well.

**Comment by pschroen** [comment]
Published rollup-plugin-glslify@1.2.0. If you can verify it's working the same as [rollup-plugin-glsl](https://github.com/vwochnik/rollup-plugin-glsl). Thanks!

**Comment by ajayns** [comment]
This looks good! I just found that a line `\n#define GLSLIFY 1\n` is injected in the string as compared to the output from rollup-plugin-glsl. I haven't tested it out on a project yet, but it looks like harmless code coming in from `glslify`. 

Since it does look like it's doing the job right, I'll close the issue. Thanks a bunch @pschroen  for your fast resolution and the API for it looks neat too.
